## Loan Status Prediction using ML Models:

In [1]:
!mamba install pandas
!mamba install numpy
!mamba install seaborn
!mamba install scikit-learn

mambajs 0.19.13

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas
Channels: emscripten-forge, conda-forge

Solving environment...
Solving took 8.301900000035763 seconds
  Name                          Version                       Build                         Channel
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
+ pandas                        3.0.2                         np22py313h9d9dc1e_0           emscripten-forge
+ python-tzdata                 2026.1                        pyhd8ed1ab_0                  conda-forge
- pip                           25.3                          pyh145f28c_0                  conda-forge
mambajs 0.19.13

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas
Channels: emscripten-forge, conda-forge

Solving environment...
Solving took 3.5478000000119208 seconds
All requested packages already installed.
mambajs 0.19.13

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas, seaborn
Channels: emscripten-forge, conda-forge

Solving environment...
Solving took 3.6945 seconds
  Name                          Version                       Build                         Channel
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
+ patsy                         1.0.2                         py313h1804a44_1               emscripten-forge
+ seaborn                       0.13.2                        hd8ed1ab_3                    conda-forge
+ seaborn-base                  0.13.2                        pyhd8ed1ab_3                  conda-forge
+ statsmodels                   0.14.6                        np22py313h3cf259a_1           emscripten-forge
mambajs 0.19.13

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas, seaborn, scikit-learn
Channels: emscripten-forge, conda-forge

Solving environment...
Solving took 4.539800000011921 seconds
  Name                          Version                       Build                         Channel
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
+ brotli-python                 1.2.0                         py313h33caa6c_0               emscripten-forge
+ certifi                       2026.2.25                     pyhd8ed1ab_0                  conda-forge
+ charset-normalizer            3.4.7                         pyhd8ed1ab_0                  conda-forge
+ idna                          3.11                          pyhd8ed1ab_0                  conda-forge
+ joblib                        1.5.3                         py313h1804a44_1               emscripten-forge
+ pysocks                       1.7.1                         py313h1804a44_2               emscripten-forge
+ requests                      2.33.1                        pyhcf101f3_0                  conda-forge
+ scikit-learn                  1.8.0                         np22py313h2c67255_3           emscripten-forge
+ setuptools                    82.0.1                        pyh332efcf_0                  conda-forge
+ threadpoolctl                 3.6.0                         pyhecae5ae_0                  conda-forge
+ urllib3                       2.2.2                         pyhd8ed1ab_0                  conda-forge

#### Importing required Python Libraries:

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
loan_data = pd.read_csv('loan_db.csv')

#### Name of Loan Dataset's Column Headers:

In [4]:
# Loan_ID : Unique Loan ID

# Gender : Male/ Female

# Married : Applicant married (Y/N)

# Dependents : Number of dependents

# Education : Applicant Education (Graduate/ Under Graduate)

# Self_Employed : Self employed (Y/N)

# ApplicantIncome : Applicant income

# CoapplicantIncome : Coapplicant income

# LoanAmount : Loan amount in thousands of dollars

# Loan_Amount_Term : Term of loan in months

# Credit_History : Credit history meets guidelines yes or no

# Property_Area : Urban/ Semi Urban/ Rural

# Loan_Status : Loan approved (Y/N) this is the target variable

In [5]:
loan_data.head(4)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y

In [6]:
loan_data.tail(4)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [7]:
print('Number of Rows:', loan_data.shape[0])
print('Number of Columns:',loan_data.shape[1])

Number of Rows: 614
Number of Columns: 13

In [8]:
loan_data['Loan_ID'] = loan_data['Loan_ID'].astype('object')
loan_data['Married'] = loan_data['Married'].astype('object')
loan_data['Dependents'] = loan_data['Dependents'].astype('object')
loan_data['Education'] = loan_data['Education'].astype('object')
loan_data['Self_Employed'] = loan_data['Self_Employed'].astype('object')
loan_data['Property_Area'] = loan_data['Property_Area'].astype('object')
loan_data['Loan_Status'] = loan_data['Loan_Status'].astype('object')

In [9]:
loan_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    str
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(7), str(1)
memory usage: 43.2+ KB

#### Handling Missing (or) Null Values

In [10]:
loan_data.isnull()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,False,False,False,False,False,False,False,False,True,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,False,False,False,False,False,False,False,False,False,False,False,False,False
610,False,False,False,False,False,False,False,False,False,False,False,False,False
611,False,False,False,False,False,False,False,False,False,False,False,False,False
612,False,False,False,False,False,False,False,False,False,False,False,False,False
613,False,False,False,False,False,False,False,False,False,False,False,False,False

In [11]:
loan_data.isnull().sum()*100 / len(loan_data)

Loan_ID              0.000000
Gender               2.117264
Married              0.488599
Dependents           2.442997
Education            0.000000
Self_Employed        5.211726
ApplicantIncome      0.000000
CoapplicantIncome    0.000000
LoanAmount           3.583062
Loan_Amount_Term     2.280130
Credit_History       8.143322
Property_Area        0.000000
Loan_Status          0.000000
dtype: float64

In [12]:
loan_data.head(2)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N

In [13]:
loan_data = loan_data.drop(['Loan_ID'], axis = 1)

In [14]:
loan_data.head(3)

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y

In [15]:
columns = ['Gender', 'Dependents', 'LoanAmount', 'Loan_Amount_Term']

In [16]:
loan_data = loan_data.dropna(subset = columns)

In [17]:
loan_data.isnull().sum()*100 / len(loan_data)

Gender               0.000000
Married              0.000000
Dependents           0.000000
Education            0.000000
Self_Employed        5.424955
ApplicantIncome      0.000000
CoapplicantIncome    0.000000
LoanAmount           0.000000
Loan_Amount_Term     0.000000
Credit_History       8.679928
Property_Area        0.000000
Loan_Status          0.000000
dtype: float64

In [18]:
loan_data['Self_Employed'].mode()[0]

'No'

In [19]:
loan_data['Self_Employed'] = loan_data['Self_Employed'].fillna(loan_data['Self_Employed'].mode()[0])

In [20]:
loan_data.isnull().sum()*100 / len(loan_data)

Gender               0.000000
Married              0.000000
Dependents           0.000000
Education            0.000000
Self_Employed        0.000000
ApplicantIncome      0.000000
CoapplicantIncome    0.000000
LoanAmount           0.000000
Loan_Amount_Term     0.000000
Credit_History       8.679928
Property_Area        0.000000
Loan_Status          0.000000
dtype: float64

In [21]:
loan_data['Credit_History'].unique()

array([ 1.,  0., nan])

In [22]:
loan_data['Credit_History'].mode()[0]

np.float64(1.0)

In [23]:
loan_data['Credit_History'] = loan_data['Credit_History'].fillna(loan_data['Credit_History'].mode()[0])

In [24]:
loan_data.isnull().sum()*100 / len(loan_data)

Gender               0.0
Married              0.0
Dependents           0.0
Education            0.0
Self_Employed        0.0
ApplicantIncome      0.0
CoapplicantIncome    0.0
LoanAmount           0.0
Loan_Amount_Term     0.0
Credit_History       0.0
Property_Area        0.0
Loan_Status          0.0
dtype: float64

#### Handling Categorical cols:

In [25]:
loan_data.sample(5)

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
263,Female,No,0,Graduate,No,7200,0.0,120.0,360.0,1.0,Rural,Y
589,Male,Yes,2,Graduate,Yes,2726,0.0,106.0,360.0,0.0,Semiurban,N
278,Male,Yes,0,Graduate,No,14583,0.0,436.0,360.0,1.0,Semiurban,Y
512,Male,Yes,2,Graduate,No,3283,2035.0,148.0,360.0,1.0,Urban,Y
27,Male,Yes,2,Not Graduate,No,4226,1040.0,110.0,360.0,1.0,Urban,Y

In [26]:
loan_data['Dependents']

1       1
2       0
3       0
4       0
5       2
       ..
609     0
610    3+
611     1
612     2
613     0
Name: Dependents, Length: 553, dtype: object

In [27]:
loan_data['Dependents'] = loan_data['Dependents'].replace(to_replace="3+",value='4')

In [28]:
loan_data['Dependents'].unique()

array(['1', '0', '2', '4'], dtype=object)

In [29]:
loan_data['Loan_Status'].unique()

array(['N', 'Y'], dtype=object)

In [30]:
loan_data['Gender'].unique()

<StringArray>
['Male', 'Female']
Length: 2, dtype: str

In [31]:
loan_data['Gender'] = loan_data['Gender'].map({'Male': 1, 'Female': 0}).astype('int')

In [32]:
loan_data['Gender'].unique()

array([1, 0])

In [33]:
loan_data['Self_Employed'].unique()

array(['No', 'Yes'], dtype=object)

In [34]:
loan_data['Property_Area'].unique()

array(['Rural', 'Urban', 'Semiurban'], dtype=object)

In [35]:
loan_data['Property_Area'] = loan_data['Property_Area'].map({'Rural':0,'Semiurban':2,'Urban':1}).astype('int')
loan_data['Loan_Status'] = loan_data['Loan_Status'].map({'Y':1,'N':0}).astype('int')
loan_data['Education'] = loan_data['Education'].map({'Graduate':1,'Not Graduate':0}).astype('int')
loan_data['Married'] = loan_data['Married'].map({'Yes':1,'No':0}).astype('int')

In [36]:
loan_data['Loan_Status'].unique()

array([0, 1])

In [37]:
loan_data['Self_Employed'] = loan_data['Self_Employed'].map({'Yes':1,'No':0}).astype('int')

In [38]:
loan_data.head(3)

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
1,1,1,1,1,0,4583,1508.0,128.0,360.0,1.0,0,0
2,1,1,0,1,1,3000,0.0,66.0,360.0,1.0,1,1
3,1,1,0,0,0,2583,2358.0,120.0,360.0,1.0,1,1

#### Store feature Matrix in X and response (Target) in Vector Y:

In [39]:
X = loan_data.drop('Loan_Status', axis = 1)

In [40]:
X.head(4)

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
1,1,1,1,1,0,4583,1508.0,128.0,360.0,1.0,0
2,1,1,0,1,1,3000,0.0,66.0,360.0,1.0,1
3,1,1,0,0,0,2583,2358.0,120.0,360.0,1.0,1
4,1,0,0,1,0,6000,0.0,141.0,360.0,1.0,1

In [41]:
y = loan_data['Loan_Status']

In [42]:
y

1      0
2      1
3      1
4      1
5      1
      ..
609    1
610    1
611    1
612    1
613    0
Name: Loan_Status, Length: 553, dtype: int32

#### Feature Scaling:

In [43]:
loan_data.head(4)

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
1,1,1,1,1,0,4583,1508.0,128.0,360.0,1.0,0,0
2,1,1,0,1,1,3000,0.0,66.0,360.0,1.0,1,1
3,1,1,0,0,0,2583,2358.0,120.0,360.0,1.0,1,1
4,1,0,0,1,0,6000,0.0,141.0,360.0,1.0,1,1

In [44]:
cols = ['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term']

In [45]:
from sklearn.preprocessing import StandardScaler
st = StandardScaler()
X[cols] = st.fit_transform(X[cols])

In [46]:
X.head(5)

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
1,1,1,1,1,0,-0.128694,-0.049699,-0.214368,0.279961,1.0,0
2,1,1,0,1,1,-0.394296,-0.545638,-0.952675,0.279961,1.0,1
3,1,1,0,0,0,-0.464262,0.229842,-0.309634,0.279961,1.0,1
4,1,0,0,1,0,0.109057,-0.545638,-0.059562,0.279961,1.0,1
5,1,1,2,1,1,0.011239,0.834309,1.440866,0.279961,1.0,1

#### Splitting The Dataset Into Training Set - Test Set & Applying K-Fold Cross Validation:

In [47]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score

In [48]:
model_df={}
def model_val(model,X,y):
    X_train, X_test, y_train, y_test = train_test_split(X,y,
                                                    test_size =0.20,
                                                    random_state =42)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    print(f"{model} accuracy is {accuracy_score(y_test, y_pred)}")

    #5-fold Cross-Validation:
    score = cross_val_score(model, X, y, cv = 5)
    print(f"{model} Avg cross val score is {np.round(np.mean(score),3):.3f}")
    model_df[model]= round(np.mean(score)*100,2)

    # print(f"{model} Avg cross val score is {np.round(np.mean(score), 3):.3f}")

#### Logistic Regression:

In [49]:
loan_data.head(4)

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
1,1,1,1,1,0,4583,1508.0,128.0,360.0,1.0,0,0
2,1,1,0,1,1,3000,0.0,66.0,360.0,1.0,1,1
3,1,1,0,0,0,2583,2358.0,120.0,360.0,1.0,1,1
4,1,0,0,1,0,6000,0.0,141.0,360.0,1.0,1,1

In [50]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model_val(model,X,y)

LogisticRegression() accuracy is 0.8018018018018018
LogisticRegression() Avg cross val score is 0.805

In [51]:
model_df

{LogisticRegression(): np.float64(80.48)}

#### Support Vector Classifier (SVC):

In [52]:
from sklearn import svm
model = svm.SVC()
model_val(model,X,y)

SVC() accuracy is 0.7927927927927928
SVC() Avg cross val score is 0.794

#### Decision Tree Classifier:

In [53]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model_val(model,X,y)

DecisionTreeClassifier() accuracy is 0.7297297297297297
DecisionTreeClassifier() Avg cross val score is 0.705

In [54]:
model_df

{LogisticRegression(): np.float64(80.48),
 SVC(): np.float64(79.39),
 DecisionTreeClassifier(): np.float64(70.53)}

#### Random Forest Classifier:

In [55]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model_val(model,X,y)

RandomForestClassifier() accuracy is 0.7837837837837838
RandomForestClassifier() Avg cross val score is 0.785

#### Gradient Boosting Classifier:

In [56]:
from sklearn.ensemble import GradientBoostingClassifier
model =GradientBoostingClassifier()
model_val(model,X,y)

GradientBoostingClassifier() accuracy is 0.7927927927927928
GradientBoostingClassifier() Avg cross val score is 0.776

#### Result: Logistic Regression is the best model with 80.48 %

In [57]:
model_df

{LogisticRegression(): np.float64(80.48),
 SVC(): np.float64(79.39),
 DecisionTreeClassifier(): np.float64(70.53),
 RandomForestClassifier(): np.float64(78.49),
 GradientBoostingClassifier(): np.float64(77.58)}

#### Performing 'Hyperparameter' Tuning (for better accuracy):

In [58]:
from sklearn.model_selection import RandomizedSearchCV

#### 1. Tune 'Hyper Parameter' for Logistic Regression:

In [59]:
log_reg_grid = {"C":np.logspace(-4,4,20),
             "solver":['liblinear']}

In [60]:
rs_log_reg = RandomizedSearchCV(LogisticRegression(),
                   param_distributions=log_reg_grid,
                  n_iter=20,cv=5,verbose=True)

In [61]:
rs_log_reg.fit(X,y)

Fitting 5 folds for each of 20 candidates, totalling 100 fits

RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_iter=20,
                   param_distributions={'C': array([1.00000000e-04, 2.63665090e-04, 6.95192796e-04, 1.83298071e-03,
       4.83293024e-03, 1.27427499e-02, 3.35981829e-02, 8.85866790e-02,
       2.33572147e-01, 6.15848211e-01, 1.62377674e+00, 4.28133240e+00,
       1.12883789e+01, 2.97635144e+01, 7.84759970e+01, 2.06913808e+02,
       5.45559478e+02, 1.43844989e+03, 3.79269019e+03, 1.00000000e+04]),
                                        'solver': ['liblinear']},
                   verbose=True)

In [62]:
rs_log_reg.best_score_

np.float64(0.8047829647829647)

In [63]:
rs_log_reg.best_params_

{'solver': 'liblinear', 'C': np.float64(0.23357214690901212)}

#### 2.'Hyper Parameter' tuning for SVC:

In [64]:
svc_grid = {'C':[0.25,0.50,0.75,1],"kernel":["linear"]}

In [65]:
rs_svc = RandomizedSearchCV(svm.SVC(), param_distributions =svc_grid, cv =5,
                   n_iter = 20, verbose = True)

In [66]:
rs_svc.fit(X,y)

/lib/python3.13/site-packages/sklearn/model_selection/_search.py:324: UserWarning: The total space of parameters 4 is smaller than n_iter=20. Running 4 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

Fitting 5 folds for each of 4 candidates, totalling 20 fits

RandomizedSearchCV(cv=5, estimator=SVC(), n_iter=20,
                   param_distributions={'C': [0.25, 0.5, 0.75, 1],
                                        'kernel': ['linear']},
                   verbose=True)

In [67]:
rs_svc.best_score_

np.float64(0.8066011466011467)

#### 3. 'Hyper Parameter' tuning for Random Forest Classifier:

In [68]:
RandomForestClassifier()

RandomForestClassifier()

In [69]:
rf_grid = {'n_estimators':np.arange(10,1000,10),
           'max_features':['auto','sqrt'],
           'max_depth':[None,3,5,10,20,30],
           'min_samples_split':[2,5,20,50,100],
           'min_samples_leaf':[1,2,5,10]
 }

In [70]:
rs_rf = RandomizedSearchCV(RandomForestClassifier(), param_distributions = rf_grid,
                   cv=5, n_iter=20, verbose =True)

In [71]:
rs_rf.fit(X,y)

Fitting 5 folds for each of 20 candidates, totalling 100 fits

/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:490: FitFailedWarning:
55 fits failed out of a total of 100.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
55 fits failed with the following error:
Traceback (most recent call last):
  File "/lib/python3.13/site-packages/sklearn/model_selection/_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.13/site-packages/sklearn/base.py", line 1329, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/lib/python3.13/site-packages/sklearn/base.py", line 492, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/lib/python3.13/site-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/lib/python3.13/site-packages/sklearn/model_selection/_search.py:1137: UserWarning: One or more of the test scores are non-finite: [0.79028665        nan        nan        nan 0.80479934 0.80660115
        nan        nan 0.80660115        nan 0.80299754 0.80661753
        nan        nan 0.80660115        nan        nan 0.80478296
        nan 0.79755938]
  warnings.warn(

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(), n_iter=20,
                   param_distributions={'max_depth': [None, 3, 5, 10, 20, 30],
                                        'max_features': ['auto', 'sqrt'],
                                        'min_samples_leaf': [1, 2, 5, 10],
                                        'min_samples_split': [2, 5, 20, 50,
                                                              100],
                                        'n_estimators': array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260,
       270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390,
       400, 410, 420, 430, 440, 450, 460, 470, 480, 490, 500, 510, 520,
       530, 540, 550, 560, 570, 580, 590, 600, 610, 620, 630, 640, 650,
       660, 670, 680, 690, 700, 710, 720, 730, 740, 750, 760, 770, 780,
       790, 800, 810, 820, 830, 840, 850, 860, 870, 880, 890, 900, 910,
       920, 930, 940, 950, 960, 970, 980, 990])},
                   verbose=True)

In [72]:
rs_rf.best_params_

{'n_estimators': np.int32(200),
 'min_samples_split': 20,
 'min_samples_leaf': 5,
 'max_features': 'sqrt',
 'max_depth': 20}

In [73]:
rs_rf.best_score_

np.float64(0.8066175266175266)

#### Results Comparison:

In [ ]:
LogisticRegression score Before Hyperparameter Tuning: 80.48
LogisticRegression score after Hyperparameter Tuning: 80.48 
    
------------------------------------------------------
SVC score Before Hyperparameter Tuning: 79.38
SVC score after Hyperparameter Tuning: 80.66
    
--------------------------------------------------------
RandomForestClassifier score Before Hyperparameter Tuning: 77.76
RandomForestClassifier score after Hyperparameter Tuning: 80.66

##### Random Forest Classifier had the greatest improvement in accuracy.
##### So, will select 'Random Forest Classifier' model for production !!

#### Let's train our best Model (RFC) on the entire Loan Dataset:

In [75]:
X = loan_data.drop('Loan_Status',axis=1)
y = loan_data['Loan_Status']

In [76]:
rf = RandomForestClassifier(n_estimators = 390, min_samples_split = 50,
   min_samples_leaf = 2,
   max_features = 'sqrt',
   max_depth = 5)

In [77]:
rf.fit(X,y)

RandomForestClassifier(max_depth=5, min_samples_leaf=2, min_samples_split=50,
                       n_estimators=390)

#### Save the Model:

In [78]:
import joblib

In [79]:
joblib.dump(rf,'loan_status_prediction')

['loan_status_prediction']

In [80]:
main_model = joblib.load('loan_status_prediction')

In [81]:
main_model

RandomForestClassifier(max_depth=5, min_samples_leaf=2, min_samples_split=50,
                       n_estimators=390)

#### GUI

In [88]:
# from tkinter import *
# import joblib
# import pandas as pd

In [89]:
# def show_entry():
    
#     p1 = float(e1.get())
#     p2 = float(e2.get())
#     p3 = float(e3.get())
#     p4 = float(e4.get())
#     p5 = float(e5.get())
#     p6 = float(e6.get())
#     p7 = float(e7.get())
#     p8 = float(e8.get())
#     p9 = float(e9.get())
#     p10 = float(e10.get())
#     p11 = float(e11.get())
    
#     model = joblib.load('loan_status_prediction')
#     df = pd.DataFrame({
#     'Gender':p1,
#     'Married':p2,
#     'Dependents':p3,
#     'Education':p4,
#     'Self_Employed':p5,
#     'ApplicantIncome':p6,
#     'CoapplicantIncome':p7,
#     'LoanAmount':p8,
#     'Loan_Amount_Term':p9,
#     'Credit_History':p10,
#     'Property_Area':p11
# },index=[0])
#     result = model.predict(df)
    
#     if result == 1:
#         Label(master, text="Loan approved").grid(row=31)
#     else:
#         Label(master, text="Loan Not Approved").grid(row=31)
        
    
# # master =Tk()
# master.title("Loan Status Prediction Using Machine Learning")
# label = Label(master,text = "Loan Status Prediction",bg = "black",
#                fg = "white").grid(row=0,columnspan=2)

# Label(master,text = "Gender [1:Male ,0:Female]").grid(row=1)
# Label(master,text = "Married [1:Yes,0:No]").grid(row=2)
# Label(master,text = "Dependents [1,2,3,4]").grid(row=3)
# Label(master,text = "Education").grid(row=4)
# Label(master,text = "Self_Employed").grid(row=5)
# Label(master,text = "ApplicantIncome").grid(row=6)
# Label(master,text = "CoapplicantIncome").grid(row=7)
# Label(master,text = "LoanAmount").grid(row=8)
# Label(master,text = "Loan_Amount_Term").grid(row=9)
# Label(master,text = "Credit_History").grid(row=10)
# Label(master,text = "Property_Area").grid(row=11)


# e1 = Entry(master)
# e2 = Entry(master)
# e3 = Entry(master)
# e4 = Entry(master)
# e5 = Entry(master)
# e6 = Entry(master)
# e7 = Entry(master)
# e8 = Entry(master)
# e9 = Entry(master)
# e10 = Entry(master)
# e11 = Entry(master)


# e1.grid(row=1,column=1)
# e2.grid(row=2,column=1)
# e3.grid(row=3,column=1)
# e4.grid(row=4,column=1)
# e5.grid(row=5,column=1)
# e6.grid(row=6,column=1)
# e7.grid(row=7,column=1)
# e8.grid(row=8,column=1)
# e9.grid(row=9,column=1)
# e10.grid(row=10,column=1)
# e11.grid(row=11,column=1)

# Button(master,text="Predict",command=show_entry).grid()

# mainloop()